### ISSUE TITLE
Basic C# Datatype is missing

### ISSUE THREAD

**Issue by Zeroks77** [DaraOladapo/c-sharp-with-dotnet-core#1]
Hey, i just walked over your repo and recognized, that you missed to explain the boolean type. 
In my opinion one of the most important datatypes.

You should explain the deeper meaning. What use is a float if I can take a double?
For what, for what and why which data type should and will be used.

**Comment by DaraOladapo** [comment]
Thanks for this.
Added bool to the code sample.
Will work on the documentation later.
