### ISSUE TITLE
The Readme

### ISSUE THREAD

**Issue by Zeroks77** [DaraOladapo/c-sharp-with-dotnet-core#2]
Hey ^^,
here is an other idea.

Since you have planned 20 lessons so far, I recommend that you move the individual lessons into the individual folders for a better clarity. In this way you prevent the markdownfile from becoming very long and remaining clear.

**Comment by DaraOladapo** [comment]
Thanks very much.
Done.
Generated a readme for the first section and linked the main readme to it.
![image](https://user-images.githubusercontent.com/4347646/65239859-cb96eb00-dad7-11e9-9dd9-109d40eb6520.png)
